"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KNOWN_ICON_NAME_SET = exports.KNOWN_ICON_NAMES = void 0;
exports.KNOWN_ICON_NAMES = [
    "Activity",
    "ArrowRight",
    "BarChart3",
    "Bell",
    "Bot",
    "Brain",
    "Briefcase",
    "Building2",
    "CalendarCheck2",
    "ChartColumn",
    "ChartNoAxesCombined",
    "CircleHelp",
    "ClipboardList",
    "Cog",
    "Database",
    "Factory",
    "Gauge",
    "Globe",
    "Headphones",
    "Headset",
    "HeartHandshake",
    "HelpCircle",
    "Layers3",
    "LayoutGrid",
    "LineChart",
    "Mail",
    "MessageCircleMore",
    "MessageSquare",
    "Mic",
    "MonitorSmartphone",
    "Phone",
    "PhoneCall",
    "Rocket",
    "Settings2",
    "ShieldCheck",
    "ShoppingCart",
    "Sparkles",
    "Stethoscope",
    "Users",
    "Workflow",
    "Wrench",
    "Zap"
];
exports.KNOWN_ICON_NAME_SET = new Set(exports.KNOWN_ICON_NAMES);
