export const KNOWN_ICON_NAMES = [
  "Activity",
  "ArrowRight",
  "BarChart3",
  "Bell",
  "Bot",
  "Brain",
  "Briefcase",
  "Building2",
  "CalendarCheck2",
  "ChartColumn",
  "ChartNoAxesCombined",
  "CircleHelp",
  "ClipboardList",
  "Cog",
  "Database",
  "Factory",
  "Gauge",
  "Globe",
  "Headphones",
  "Headset",
  "HeartHandshake",
  "HelpCircle",
  "Layers3",
  "LayoutGrid",
  "LineChart",
  "Mail",
  "MessageCircleMore",
  "MessageSquare",
  "Mic",
  "MonitorSmartphone",
  "Phone",
  "PhoneCall",
  "Rocket",
  "Settings2",
  "ShieldCheck",
  "ShoppingCart",
  "Sparkles",
  "Stethoscope",
  "Users",
  "Workflow",
  "Wrench",
  "Zap"
] as const;

export const KNOWN_ICON_NAME_SET = new Set(KNOWN_ICON_NAMES);
