import type { SectionKey } from "@prisma/client";

export const SECTION_KEYS: SectionKey[] = [
  "PRODUCT_SHOWCASE_OVERVIEW",
  "HERO_SECTION",
  "PRODUCT_SHOWCASE_SECTION",
  "PARTNERSHIP_SECTION",
  "VOICE_AGENTS_SECTION",
  "AUTOMATION_ENGINES_SECTION",
  "MODEL_CREATION_GRID_SECTION",
  "ROI_SNAPSHOT_SECTION",
  "PROCESS_STEPS_SECTION",
  "POWERFUL_PRODUCTS_OVERVIEW_SECTION",
  "CALLER_SHOWCASE_SECTION",
  "TESTIMONIALS_SECTION",
  "FAQ_SECTION",
  "INTEGRATIONS_SECTION",
  "SUPPORT_LEAD_FORM_SECTION",
  "SITE_FOOTER_SECTION",
  "HEADER",
  "CHAT"
];
